### ISSUE TITLE
Docs: Try to help with documentation

### ISSUE THREAD

**Issue by geekabel** [laurentmuller/fpdf2#1]
Thanks for rewriting this package. Since the time I wanted to take the time to do it. 
I'd like to add some documentation to help other people better understand this new package.  
I saw that you had used it in the `calculation` project. 
Here's an example of how I think it works 

``` php
$pdf = new PdfDocument();
$pdf->addPage();
$pdf->setFont('Arial','B',16);
$pdf->cell(40,10,'Hello World!');
$pdf->output(PdfDestination::INLINE, 'hello'); // PdfDestination::INLINE by default

```

Alternatively you can extend as a typical php class and add your own custom scripts.

```php
class CustomPdf extends PdfDocument
{
    public function __construct(
        $orientation = PdfOrientation::PORTRAIT,
        $unit = PdfUnit::MILLIMETER,
        $size = PdfPageSize::A4
    ) {
        parent::__construct( $orientation, $unit, $size );
    }
}
```

**Comment by laurentmuller** [comment]
Hi,

Any help is welcome !

Just fork this repository do change and create a PR.

**Comment by laurentmuller** [comment]
Just comment about your first example. You can also use the enumeration values:

```php
$pdf = new PdfDocument();
$pdf->addPage();
$pdf->setFont(PdfFontName::ARIAL, PdfFontStyle::BOLD, 16);
$pdf->cell(40, 10, 'Hello World!');
```

**Comment by laurentmuller** [comment]
For you information:

I have created some tutorials on the `doc` folder.

**Comment by geekabel** [comment]
Hey, thanks you ! I will look at it . I added documentation similar to that in the old version of FPDF, but using markdown and with the new parameters for each method. I'll make a pull request for you to see.

**Comment by laurentmuller** [comment]
Added tutorials.
